config/routes.rb
Rails.application.routes.draw do
  # Semi-static routes
  get "index", to: "home#index", as: :home
  get "about", to: "home#about", as: :about
  get "contact", to: "home#contact", as: :contact
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  get "errors/404", to: "errors#error_404", as: :error_404

  get "gamedev", to: "projects#index_gamedev", as: "gamedev"
  get "webdev", to: "projects#index_webdev", as: "webdev"
  get "gameaudio", to: "projects#index_gameaudio", as: "gameaudio"
  

  # Resource routes
  resources :sessions
  resources :uploaded_files
  resources :users
  resources :file_projects
  resources :links
  resources :tag_projects
  resources :tags
  resources :projects
  
  match '*path' => 'errors#error_404', via: :all

  root "home#index"

end

app/models/uploaded_file.rb
class UploadedFile < ApplicationRecord
    mount_uploader :cw_file, CWFileUploader

    has_many :file_project
    has_many :project, through: :file_project # Realistically, I don't expect the same file to apply to more than one project... but hey, you never know
    has_many :project_thumbnail, class_name: "Project", foreign_key: "thumbnail_id"

    # Validations
    validates_presence_of :name, :media_type, :cw_file, :upload_date
    validates_date :upload_date, on_or_before: 0.days.ago
    validates_inclusion_of :media_type, in: %w[document image audio video executable archive other], message: "Not a valid media type."

    # Scopes
    scope :alphabetical,    lambda {order(:name)}
    scope :chronological,   lambda {order(:upload_date)}
    scope :has_media_type,  lambda {|t| where("media_type = ?", "#{t}")}
    scope :not_media_type,  lambda {|t| where("media_type != ?", "#{t}")}
    scope :active,          lambda {where(active: true)}
    scope :inactive,        lambda {where(active: false)}

    # Callbacks
    after_create :set_upload_date 
    before_destroy do
        check_destroyable?
        if errors.present? then throw(:abort) end
    end

    # Methods
    def activate()
        self.active = true
        self.save!
    end

    def deactivate()
        self.active = false
        self.save!
    end

    def set_upload_date()
        self.upload_date = 0.days.ago
        self.save!
    end
    
    def url()
        self.cw_file.url
    end

    private
        def check_destroyable?()
            unless self.project.size == 0 then
                errors.add(:base, "This file cannot be deleted because it's currently being used by one or more projects. You should deactivate it instead.")
            end
        end

end

app/controllers/uploaded_files_controller.rb
class UploadedFilesController < ApplicationController
  before_action :set_uploaded_file, only: [:show, :edit, :update, :destroy]
  authorize_resource

  # GET /uploaded_files
  # GET /uploaded_files.json
  def index
    @uploaded_files = UploadedFile.all
  end

  # GET /uploaded_files/1
  # GET /uploaded_files/1.json
  def show
  end

  # GET /uploaded_files/new
  def new
    @uploaded_file = UploadedFile.new
  end

  # GET /uploaded_files/1/edit
  def edit
  end

  # POST /uploaded_files
  # POST /uploaded_files.json
  def create
    @uploaded_file = UploadedFile.new(uploaded_file_params)

    respond_to do |format|
      if @uploaded_file.save
        format.html { redirect_to @uploaded_file, notice: 'Uploaded file was successfully created.' }
        format.json { render :show, status: :created, location: @uploaded_file }
      else
        format.html { render :new }
        format.json { render json: @uploaded_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploaded_files/1
  # PATCH/PUT /uploaded_files/1.json
  def update
    respond_to do |format|
      if @uploaded_file.update(uploaded_file_params)
        format.html { redirect_to @uploaded_file, notice: 'Uploaded file was successfully updated.' }
        format.json { render :show, status: :ok, location: @uploaded_file }
      else
        format.html { render :edit }
        format.json { render json: @uploaded_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploaded_files/1
  # DELETE /uploaded_files/1.json
  def destroy
    @uploaded_file.destroy
    respond_to do |format|
      format.html { redirect_to uploaded_files_url, notice: 'Uploaded file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uploaded_file
      @uploaded_file = UploadedFile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def uploaded_file_params
      params.require(:uploaded_file).permit(:name, :media_type, :upload_date, :active, :cw_file)
    end
end

app/helpers/uploaded_files_helper.rb
module UploadedFilesHelper
end

app/views/uploaded_files/_form.html.erb
<%= form_with(model: uploaded_file, local: true) do |form| %>
  <% if uploaded_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uploaded_file.errors.count, "error") %> prohibited this uploaded_file from being saved:</h2>

      <ul>
      <% uploaded_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cw_file, "Upload a file:" %>
    <%= form.file_field :cw_file %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :media_type %>
    <%= form.select :media_type, ["image", "audio", "video", "executable", "document", "archive", "other"] %>
  </div>

  <div class="field hidden">
    <%= form.label :upload_date %>
    <%= form.date_select :upload_date %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, checked: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uploaded_files/edit.html.erb
<h2>Editing Uploaded File</h2>

<%= render 'form', uploaded_file: @uploaded_file %>

<%= link_to 'Show', @uploaded_file %> |
<%= link_to 'Back', uploaded_files_path %>

app/views/uploaded_files/index.html.erb
<%= render partial: "layouts/flash" %>

<h2>Uploaded Files</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Media type</th>
      <th>Upload date</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploaded_files.each do |uploaded_file| %>
      <tr>
        <td><%= uploaded_file.name %></td>
        <td><%= uploaded_file.url.split('?').first + "?[...]" %></td>
        <td><%= uploaded_file.media_type %></td>
        <td><%= uploaded_file.upload_date %></td>
        <td><%= uploaded_file.active %></td>
        <td><%= link_to 'Show', uploaded_file %></td>
        <td><%= link_to 'Edit', edit_uploaded_file_path(uploaded_file) %></td>
        <td><%= link_to 'Destroy', uploaded_file, class: "destroy", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uploaded File', new_uploaded_file_path %>

app/views/uploaded_files/new.html.erb
<h2>New Uploaded File</h2>

<%= render 'form', uploaded_file: @uploaded_file %>

<%= link_to 'Back', uploaded_files_path %>

app/views/uploaded_files/show.html.erb
<%= render partial: "layouts/flash" %>

<p>
  <strong>Name:</strong>
  <%= @uploaded_file.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @uploaded_file.url %>
</p>

<p>
  <strong>Media type:</strong>
  <%= @uploaded_file.media_type %>
</p>

<p>
  <strong>Upload date:</strong>
  <%= @uploaded_file.upload_date %>
</p>

<p>
  <strong>Active:</strong>
  <%= @uploaded_file.active %>
</p>

<%= link_to 'Edit', edit_uploaded_file_path(@uploaded_file) %> |
<%= link_to 'Back', uploaded_files_path %>