config/routes.rb
Rails.application.routes.draw do
  # Semi-static routes
  get "index", to: "home#index", as: :home
  get "about", to: "home#about", as: :about
  get "contact", to: "home#contact", as: :contact
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  get "errors/404", to: "errors#error_404", as: :error_404

  get "gamedev", to: "projects#index_gamedev", as: "gamedev"
  get "webdev", to: "projects#index_webdev", as: "webdev"
  get "gameaudio", to: "projects#index_gameaudio", as: "gameaudio"
  

  # Resource routes
  resources :sessions
  resources :uploaded_files
  resources :users
  resources :file_projects
  resources :links
  resources :tag_projects
  resources :tags
  resources :projects
  
  match '*path' => 'errors#error_404', via: :all

  root "home#index"

end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tag_projects
    has_many :tags, through: :tag_projects
    has_many :links
    has_many :file_projects
    has_many :uploaded_files, through: :file_projects
    belongs_to :thumbnail, class_name: "UploadedFile"

    # Validations
    validates_presence_of :name, :start_date, :priority
    validates_numericality_of :priority, only_integer: true
    validates_date :start_date
    validates_date :end_date, on_or_after: :start_date, allow_nil: true
    validate :ensure_thumbnail_is_image

    # Scopes
    scope :alphabetical,    lambda {order(:name)}
    scope :chronological,   lambda {order(:start_date, :end_date)}
    scope :by_priority,     lambda {order(:priority)}
    scope :for_tag,         lambda {|t| joins(:tag).where('tag.name = ?', "#{t}")}
    scope :for_category,    lambda {|c| where('category = ?', "#{c}")}
    scope :untagged,        lambda {where('id NOT IN (?)', Tag_Project.map{|t| t.project_id})}
    scope :current,         lambda {where('end_date IS NULL')}
    scope :completed,       lambda {where('end_date IS NOT NULL')}
    scope :active,          lambda {where(active: true)}
    scope :inactive,        lambda {where(active: false)}

    # Methods
    def activate()
        self.active = true
        self.save!
    end

    def deactivate()
        self.active = false
        self.save!
    end

    # Return a string showing the date range of this project. 
    # e.g. September 2016 – December 2017, May 2020 – present, 
    # "June 2020" (if both dates in the same month)
    def date_range()
        output = self.start_date.strftime("%B %Y")
        if end_date.nil? then
            output += " – " + "present"
        else
            e_d = self.end_date.strftime("%B %Y")
            if output == e_d then return output end
            output += " – " + e_d
        end
        return output
    end

    def num_tags()
        return self.tags.size
    end

    def num_files()
        return self.uploaded_files.size
    end

    def num_links()
        return self.links.size
    end

    def has_tags?()
        return (self.num_tags > 0)
    end

    def has_files?()
        return (self.num_files > 0)
    end

    def has_links?()
        return (self.num_links > 0)
    end

    def has_thumbnail?()
        return (not self.thumbnail_id.nil?)
    end

    private
        def ensure_thumbnail_is_image()
            if self.has_thumbnail? and self.thumbnail.media_type != "image" then
                errors.add(:thumbnail, "must be an image")
            end
        end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_resources, only: [:new, :edit, :update]
  authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    if logged_in_as_webmaster?
      @projects = Project.all
    else
      @projects = Project.active
    end
    @title = "All"
  end

  def index_gamedev
    @projects = Project.for_category("Game Development").by_priority
    if not logged_in_as_webmaster?
      @projects = @projects.active
    end
    @title = "Game Development"
    render :index
  end

  def index_webdev
    @projects = Project.for_category("Web Development").by_priority
    if not logged_in_as_webmaster?
      @projects = @projects.active
    end
    @title = "Web Development"
    render :index
  end

  def index_gameaudio
    @projects = Project.for_category("Game Audio").by_priority
    if not logged_in_as_webmaster?
      @projects = @projects.active
    end
    @title = "Game Music and Sound Design"
    render :index
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @gallery = @project.uploaded_files.active.has_media_type("image")
    @links = @project.links.active
    @files = @project.uploaded_files.active.not_media_type("image")
    @tags = @project.tags.active.by_name
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      if not (@project.active or logged_in_as_webmaster?) then
        flash[:error] = "Guests are not able to view that page."
        redirect_to projects_path
      end
      @back_link = back_link(@project)
    end

    def set_resources
      @thumbnails = UploadedFile.has_media_type("image").collect{|f| [f.name, f.id]}
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :start_date, :end_date, :short_description, :description, :active, :thumbnail_id, :category, :priority)
    end

    # Clicking "back" on a project show page sends to the correct index:
    def back_link(project)
      if project.active then
        if project.category == "Game Development"
            return gamedev_path
        elsif project.category == "Game Audio"
            return gameaudio_path
        elsif project.category == "Web Development"
            return webdev_path
        end
      end
      return projects_path
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_file_type_icon.html.erb
<% icons = Hash["document" => "bootstrap-icons/file_earmark_text", "image" => "bootstrap-icons/image", "audio" => "bootstrap-icons/volume_up", "video" => "bootstrap-icons/film", "executable" => "bootstrap-icons/terminal", "archive" => "bootstrap-icons/file_zip", "other" => "bootstrap-icons/files"] %>

<%= render partial: icons[file.media_type]%>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :short_description %>
    <%= form.text_area :short_description %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, checked: true %>
  </div>

  <div class="field">
    <%= form.label :thumbnail_id %>
    <%= form.select :thumbnail_id, @thumbnails, {include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, ["Game Development", "Game Audio", "Web Development", "Test Category"] %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.text_field :priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_modal.html.erb
<!-- Code largely inspired by https://getbootstrap.com/docs/4.0/components/modal/ -->
<div class="modal fade" id="gallery-modal" tabindex="-1" role="dialog" aria-labelledby="gallery-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="gallery-modal-title">New message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img class="modal-image" src="">
            </div>
        </div>
    </div>
</div>

<script>
    $("#gallery-modal").on("show.bs.modal", function(event) {
        var trigger = $(event.relatedTarget);
        console.log("trigger: ", trigger);
        var url = trigger.data("image");
        var title = trigger.data("title");
        console.log("url: ", url);
        console.log("title: ", title);
        var modal = $("#gallery-modal");

        modal.find(".modal-title").text(title);
        modal.find("img.modal-image").attr("src", url);
        modal.find("img.modal-image").attr("alt", title);

    })
</script>

app/views/projects/edit.html.erb
<h2>Editing Project</h2>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', @back_link %>

app/views/projects/index.html.erb
<%= render partial: "layouts/flash" %>

<h2><%= @title %> Projects</h2>


<ul class="projects">
  <% @projects.each do |project| %>
    <%= link_to project_path(project) do %>
      <% if project.has_thumbnail? then %>
        <li class="project hovering clickable" style="background-image: linear-gradient(to bottom, rgba(255,255,255,0.5), rgba(255,255,255,0.9)), url('<%= project.thumbnail.url %>')">
      <% else %>
        <li class="project hovering clickable">
      <% end %>
        <h4><%= project.name %></h4>
        <% if not project.short_description.nil? %>
          <p><%= project.short_description %></p>
        <% end %>
        <% if can? :edit, Project or can? :destroy, Project %>
          <hr>
          <div class="project-options">
            <% if can? :edit, Project %>
              <%= link_to 'Edit', edit_project_path(project) %>
            <% end %>
            <% if can? :destroy, Project %>
              | <%= link_to 'Destroy', project, class: "destroy", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        <% end %>

      </li>
    <% end %>
  <% end %>
</ul>

<br style="clear:left;"><br>

<% if can? :create, Project %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<!-- Project title. -->
<!-- Render a thumbnail and some extra space if one exists. -->
<% if @project.has_thumbnail? then %>
  <div class="project-title" style="background-image: linear-gradient(to bottom, rgba(255,255,255,0.4), rgba(255,255,255,1)), url('<%= asset_path(@project.thumbnail.url, type: :file) %>')">
    <%= render partial: "layouts/flash" %>
    <h2 style="margin-top: 6em;"><%= @project.name %></h2>
<% else %>
  <div class="project-title">
    <%= render partial: "layouts/flash" %>
    <h2><%= @project.name %></h2>
<% end %>
  <h5 class="dates">
    <%= @project.date_range %>  
  </h5>

  <!-- Project tags, if there are any. -->
  <% if @tags.count > 0 %>
    <div class="tags">
      <ul class="tags">
        <li><%= render partial: "bootstrap-icons/tag_fill" %></li>
        <% @tags.each do |t| %>
          <%= link_to tag_path(t) do %>
            <li class="tag"><%= t.name %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>



<hr style="clear:left;">

<% if not @project.active %>
  <p>Note: This project is currently not displayed publicly.</p>
<% end %>

<!-- Project description. -->
<!-- Despite having the least code, this is the majority of the content! -->
<%= simple_format(@project.description) %>

<!-- Gallery images, if they exist -->
<% if @gallery.count > 0 %>
  <%= render partial: "projects/modal" %>
  <h5 class="project-subheader">Gallery</h5>
  <ul class="files">
    <% @gallery.each do |f| %>
      <li class="gallery hovering clickable" data-toggle="modal" data-target="#gallery-modal" data-image=<%= asset_path(f.url, type: :file) %> data-title="<%= f.name %>">
        <img class="project-gallery" src=<%= asset_path(f.url, type: :file) %> alt="<%= f.name %>"><br>
        <div class="gallery-caption"><%= f.name %></div>
      </li>
    <% end %>
  </ul>
<% end %>

<!-- External links, if they exist -->
<% if @links.count > 0 %>
  <h5 class="project-subheader">Links</h5>
  <ul class="links">
    <% @links.each do |l| %>
        <% if l.is_soundcloud? %>
          <li class="soundcloud-embed hovering clickable">
            <%= link_to l.url, html_options = {target: "_blank"} do %>
              <p class="soundcloud-embed"><%= l.name %></p>
            <% end %>
            <% is_playlist = l.url.include?("/sets/") %>
            <iframe width="100%" height=<%= is_playlist ? "300" : "166" %> scrolling="no" frameborder="no" allow="autoplay" src=<%= "https://w.soundcloud.com/player/?url=#{l.url}&color=%23ad0dff&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true" + (is_playlist ? "&visual=true" : "") %>></iframe>
          </li>
          
        <% else %>
          <%= link_to l.url, html_options = {target: "_blank"} do %>
            <li class="link hovering clickable">
              <%= render partial: "bootstrap-icons/link_45deg" %>
              <%= l.name %>
              <%= render "bootstrap-icons/box_arrow_up-right", locals: {height: 16, width: 16} %>
            </li>
          <% end %>
        <% end %>
      
    <% end %>
  </ul>
<% end %>

<!-- Uploaded files for download, if they exist -->
<% if @files.count > 0 %>
  <h5 class="project-subheader">Files</h5>
  <ul class="files">
    <% @files.each do |f| %>
      <%= link_to asset_path(f.url, type: :file), html_options = {download: f.url.split('/').last.split('?').first} do %>
        <li class="file hovering clickable">
          <%= render partial: "projects/file_type_icon", locals: {file: f}%>
          <%= f.name %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<!-- asset_path(file.url, type: :file) -->

<br style="clear: both;">
<% if can? :edit, Project %>
  <%= link_to 'Edit', edit_project_path(@project) %> | 
<% end %>
<%= link_to 'Back', @back_link %>