config/routes.rb
Rails.application.routes.draw do
  # Semi-static routes
  get "index", to: "home#index", as: :home
  get "about", to: "home#about", as: :about
  get "contact", to: "home#contact", as: :contact
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  get "errors/404", to: "errors#error_404", as: :error_404

  get "gamedev", to: "projects#index_gamedev", as: "gamedev"
  get "webdev", to: "projects#index_webdev", as: "webdev"
  get "gameaudio", to: "projects#index_gameaudio", as: "gameaudio"
  

  # Resource routes
  resources :sessions
  resources :uploaded_files
  resources :users
  resources :file_projects
  resources :links
  resources :tag_projects
  resources :tags
  resources :projects
  
  match '*path' => 'errors#error_404', via: :all

  root "home#index"

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_projects
    has_many :projects, through: :tag_projects

    # Validations
    validates_presence_of :name, :category
    validates_uniqueness_of :name

    # Scopes
    scope :by_name,     lambda {order('name')}
    scope :by_category,     lambda {order('category')}
    scope :for_category,    lambda {|t| where('category = ?', "#{t}")}
    scope :search,      lambda {|t| where('name LIKE ?', "#{t}")}
    scope :active,      lambda {where(active: true)}
    scope :inactive,    lambda {where(active: false)}

    # Callbacks
    before_destroy do
        self.check_destroyable?
        if errors.present? then throw(:abort) end
    end
    after_rollback :deactivate

    # Methods
    def activate()
        self.active = true
        self.save!
    end

    def deactivate()
        self.active = false
        self.save!
    end

    private
        def check_destroyable?()
            unless self.projects.size == 0 then
                errors.add(:base, "This tag cannot be deleted because it's currently being used by one or more projects. It has been set to inactive instead.")
            end
        end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  authorize_resource

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.by_name
    if not logged_in_as_webmaster? then
      @tags = @tags.active
    end
    @categories = @tags.map{|t| t.category}.uniq.sort
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @projects = @tag.projects
    if not logged_in_as_webmaster? then
      @projects = @projects.active
    end
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
      if not (@tag.active or logged_in_as_webmaster?) then
        flash[:error] = "Guests are not able to view that page."
        redirect_to tags_path
      end
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name, :category, :active)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, checked: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h2>Editing Tag</h2>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<%= render partial: "layouts/flash" %>

<h2>All Tags</h2>
<hr>

<% for c in @categories do %>
  <h5><%= c %></h5>
  <ul class="tags-list">
    <% @tags.for_category(c).each do |t| %>
      <li><%= link_to t.name, t %></li>
    <% end %>
  </ul>
<% end %>

<br>

<% if can? :create, Tag %>
  <%= link_to 'New Tag', new_tag_path %>
<% end %>

app/views/tags/new.html.erb
<h2>New Tag</h2>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<%= render partial: "layouts/flash" %>

<h2><%= render partial: "bootstrap-icons/tag_fill" %> <%= @tag.name %></h2>
<h6>In category: <%= link_to @tag.category, tags_path %></h6>
<hr>

<% if not @tag.active %>
  <p>Note: This tag is currently not in use.</p>
<% end %>

<% if @projects.size == 0 %>
  <p>There are currently no projects with this tag.</p>
<% else %>
  <h4>Projects with this tag:</h4>
  <ul class="projects-for-tag">
    <% @projects.each do |p| %>
      <li><%= link_to p.name, project_path(p)%></li>
    <% end %>
  </ul>
<% end %>

<br>

<% if can? :edit, Project %>
  <%= link_to 'Edit', edit_tag_path(@tag) %> | 
<% end %>
<%= link_to 'Back', tags_path %>