config/routes.rb
Rails.application.routes.draw do
  # Semi-static routes
  get "index", to: "home#index", as: :home
  get "about", to: "home#about", as: :about
  get "contact", to: "home#contact", as: :contact
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  get "errors/404", to: "errors#error_404", as: :error_404

  get "gamedev", to: "projects#index_gamedev", as: "gamedev"
  get "webdev", to: "projects#index_webdev", as: "webdev"
  get "gameaudio", to: "projects#index_gameaudio", as: "gameaudio"
  

  # Resource routes
  resources :sessions
  resources :uploaded_files
  resources :users
  resources :file_projects
  resources :links
  resources :tag_projects
  resources :tags
  resources :projects
  
  match '*path' => 'errors#error_404', via: :all

  root "home#index"

end

app/views/layouts/_flash.html.erb
<% flash.each do |name, message| %>
    <div class="flash <%= flash[:notice] ? "notice" : "warning" %> hovering" onclick="this.remove()">
        <p><%= message %></p>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="row">
    <div class="col">
        <p class="footer">
            <%= link_to "Home", home_path, class: "footer-link" %> | 
            <%= link_to "Contact", contact_path, class: "footer-link" %> | 
            <% if logged_in? then %>
                <%= link_to "Log out", logout_path, class: "footer-link" %>
            <% else %>
                <%= link_to "Webmaster log in", login_path, class: "footer-link" %>
            <% end %>
            <br><br>
            Site contents and style &copy;2020 Jonathan Fischer. All rights reserved.
            <br><br>
        </p>
        <!--
        <p class="footer-small">
            
        </p>
        -->
    </div>
</div>

app/views/layouts/_header.html.erb
<%= link_to home_path, html_options = {class: "header"} do %>
    <h1 class="header">Jonathan Fischer</h1>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="row">
    <div class="col">
    
        <ul class="nav">
            <li class="nav-item">
                <%= link_to "About Me", home_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Game Development", gamedev_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Game Music and Sound Design", gameaudio_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Web Development", webdev_path, class: "nav-link" %>
            </li>
        </ul>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jonathan Fischer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Font link tag -->
    <link rel="stylesheet" href="https://use.typekit.net/epb5llv.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: "layouts/header" %>
      <%= render partial: "layouts/navbar" %>
      <div class="content">
        <%= yield %>
      </div>
      <br>
      <hr>
      <%= render partial: "layouts/footer" %>
    </div>
  </body>
</html>